### ISSUE TITLE
Possible fake results

### ISSUE THREAD

**Issue by bret99** [sharsil/mailcat#3]
Hi guys. There is some possible issue about protonmail results: whatever email inputed the results of protonmail provider are always present =>
*  user_name@protonmail.com
*  user_name@protonmail.ch
*  user_name@pm.me.
Is it OK?

**Comment by sharsil** [comment]
Hi, thanks for your issue! I checked it twice and a have no fake results! 
For example:
`python3 mailcat.py soxoj --tor -p proton # True results`
And:
`python3 mailcat.py soxoj12333333 --tor -p proton # No results`

Can you provide more information about it?

**Comment by bret99** [comment]
![image](https://user-images.githubusercontent.com/64787351/135472920-e1389802-58f3-4c2e-ae67-0a53315451a3.png)

**Comment by bret99** [comment]
![image](https://user-images.githubusercontent.com/64787351/135473653-badf8522-7e0e-4665-9d21-86cea262c8a2.png)

**Comment by bret99** [comment]
Besides after random input =>
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/desktop/my_opt/mailcat/mailcat.py", line 1145, in print_results
    res = checker(target, req_session_fun)
  File "/home/desktop/my_opt/mailcat/mailcat.py", line 960, in runbox
    chkRunbox = sreq.post('https://runbox.com/signup/signup', headers=headers, data=data, timeout=5)
  File "/home/desktop/.local/lib/python3.9/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/desktop/.local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/desktop/.local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/desktop/.local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: SOCKSHTTPSConnectionPool(host='runbox.com', port=443): Max retries exceeded with url: /signup/signup (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f7be17f7a30>: Failed to establish a new connection: [Errno -2] Name or service not known'))

**Comment by sharsil** [comment]
> ![image](https://user-images.githubusercontent.com/64787351/135473653-badf8522-7e0e-4665-9d21-86cea262c8a2.png)

It looks like your version is not a latest one!  here is my output
![mailcat](https://user-images.githubusercontent.com/89255524/135484724-b744eda1-0c64-4ca6-a81e-87593f327016.png)

**Comment by sharsil** [comment]
> Besides after previous random input => During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner self.run() File "/usr/lib/python3.9/threading.py", line 892, in run self._target(*self._args, **self._kwargs) File "/home/desktop/my_opt/mailcat/mailcat.py", line 1145, in print_results res = checker(target, req_session_fun) File "/home/desktop/my_opt/mailcat/mailcat.py", line 960, in runbox chkRunbox = sreq.post('https://runbox.com/signup/signup', headers=headers, data=data, timeout=5) File "/home/desktop/.local/lib/python3.9/site-packages/requests/sessions.py", line 590, in post return self.request('POST', url, data=data, json=json, **kwargs) File "/home/desktop/.local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request resp = self.send(prep, **send_kwargs) File "/home/desktop/.local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send r = adapter.send(request, **kwargs) File "/home/desktop/.local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send raise ConnectionError(e, request=request) requests.exceptions.ConnectionError: SOCKSHTTPSConnectionPool(host='runbox.com', port=443): Max retries exceeded with url: /signup/signup (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f7be17f7a30>: Failed to establish a new connection: [Errno -2] Name or service not known'))

May be you forgot to start your  tor service? If Proton Mail service is available in your country then you don't need to use `--tor` option (;

**Comment by soxoj** [comment]
Hey, I also don't see this behavior. Could you please specify additional information about your environment, e.g. ISP or plaintext answer of Protonmail?

**Comment by benjiworld** [comment]
It simply doesn't work... I've tested with my own usernames and..no results..., furthermore fake usernames always found on Google...

**Comment by soxoj** [comment]
Fixed in #57
